# -*- coding: utf-8 -*-
"""suc_llmGOlocally.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDznXvsfQG-9Uluyik-eM7CYbvV-VPbS
"""

!wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
!rm -rf /usr/local/go
!tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
!export PATH=$PATH:/usr/local/go/bin

import os
os.environ['PATH'] += ":/usr/local/go/bin"

!go version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile hello.go
# package main
# import "fmt"
# func main() {
#     fmt.Println("Hello from Go in Colab!")
# }
#

!go run hello.go

!go install github.com/sjwhitworth/golearn@latest

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/naive"
# )
# 
# func main() {
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     cls := naive.NewBernoulliNBClassifier()
#     cls.Fit(trainData)
# 
#     predictions, err := cls.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     confMatrix, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(confMatrix))
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %cd go_project

!go run /content/main.go

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /content/go_project
# %cd /content/go_project

!go mod init go_project

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/naive"
# )
# 
# func main() {
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     cls := naive.NewBernoulliNBClassifier()
#     cls.Fit(trainData)
# 
#     predictions, err := cls.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     confMatrix, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(confMatrix))
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile iris.csv
# sepal_length,sepal_width,petal_length,petal_width,class
# 5.1,3.5,1.4,0.2,Iris-setosa
# 4.9,3.0,1.4,0.2,Iris-setosa
# 4.7,3.2,1.3,0.2,Iris-setosa
# 4.6,3.1,1.5,0.2,Iris-setosa
# 5.0,3.6,1.4,0.2,Iris-setosa
# 5.4,3.9,1.7,0.4,Iris-setosa
# 6.4,3.2,4.5,1.5,Iris-versicolor
# 6.9,3.1,4.9,1.5,Iris-versicolor
# 5.5,2.3,4.0,1.3,Iris-versicolor
# 6.5,2.8,4.6,1.5,Iris-versicolor
# 7.6,3.0,6.6,2.1,Iris-virginica
# 4.9,2.5,4.5,1.7,Iris-virginica
# 7.3,2.9,6.3,1.8,Iris-virginica
# 6.7,2.5,5.8,1.8,Iris-virginica
# 6.5,3.0,5.8,2.2,Iris-virginica
#

!go get github.com/sjwhitworth/golearn/base
!go get github.com/sjwhitworth/golearn/evaluation
!go get github.com/sjwhitworth/golearn/naive

!go run main.go









# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /content/go_project
# %cd /content/go_project
!go mod init go_project
!go get github.com/sjwhitworth/golearn@latest

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/naive"
# )
# 
# func main() {
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     cls := naive.NewBernoulliNBClassifier()
#     cls.Fit(trainData)
# 
#     predictions, err := cls.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     confMatrix, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(confMatrix))
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile iris.csv
# sepal_length,sepal_width,petal_length,petal_width,class
# 5.1,3.5,1.4,0.2,Iris-setosa
# 4.9,3.0,1.4,0.2,Iris-setosa
# 4.7,3.2,1.3,0.2,Iris-setosa
# 4.6,3.1,1.5,0.2,Iris-setosa
# 5.0,3.6,1.4,0.2,Iris-setosa
# 6.4,3.2,4.5,1.5,Iris-versicolor
# 6.9,3.1,4.9,1.5,Iris-versicolor
# 5.5,2.3,4.0,1.3,Iris-versicolor
# 7.6,3.0,6.6,2.1,Iris-virginica
# 6.5,3.0,5.8,2.2,Iris-virginica
# 
#

!go run /content/go_project/main.go

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/naive"
# )
# 
# func main() {
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     cls := naive.NewGaussianNBClassifier()
#     cls.Fit(trainData)
# 
#     predictions, err := cls.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     confMatrix, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(confMatrix))
# }
#

!go run main.go

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/naive"
# )
# 
# func main() {
#     // تحميل بيانات Iris
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     // تقسيم البيانات
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     // استخدام GaussianNB المناسب للبيانات المستمرة
#     cls := naive.NewGaussianNBClassifier()
#     cls.Fit(trainData)
# 
#     // التنبؤ
#     predictions, err := cls.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     // التقييم
#     confMatrix, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(confMatrix))
# }
#

"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
#     "fmt"
#     "github.com/sjwhitworth/golearn/base"
#     "github.com/sjwhitworth/golearn/evaluation"
#     "github.com/sjwhitworth/golearn/trees"
# )
# 
# func main() {
#     // تحميل البيانات
#     rawData, err := base.ParseCSVToInstances("iris.csv", true)
#     if err != nil {
#         panic(err)
#     }
# 
#     // تقسيم البيانات
#     trainData, testData := base.InstancesTrainTestSplit(rawData, 0.70)
# 
#     // تدريب نموذج شجرة القرار
#     tree := trees.NewID3DecisionTree(0.6)
#     err = tree.Fit(trainData)
#     if err != nil {
#         panic(err)
#     }
# 
#     // التنبؤ
#     predictions, err := tree.Predict(testData)
#     if err != nil {
#         panic(err)
#     }
# 
#     // التقييم
#     cm, err := evaluation.GetConfusionMatrix(testData, predictions)
#     if err != nil {
#         panic(err)
#     }
# 
#     fmt.Println(evaluation.GetSummary(cm))
# }
#

!wget https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv -O iris.csv

!curl -o iris.csv https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv

!go run main.go

"""#############################################"""

















!go get github.com/openai/openai-go

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
# 	"context"
# 	"fmt"
# 	"log"
# 
# 	"github.com/openai/openai-go/v3"
# )
# 
# func main() {
# 	// أدخل مفتاح API الخاص بك هنا
# 	apiKey := "YOUR_API_KEY"
# 
# 	// إعداد العميل
# 	client := openai.NewClient(apiKey)
# 
# 	// إرسال طلب لإنشاء نص باستخدام GPT-2
# 	response, err := client.Completions.Create(context.Background(), openai.CompletionRequest{
# 		Model:  openai.GPT3TextDavinci003, // استخدم النموذج المناسب
# 		Prompt: "مرحباً، كيف يمكنني مساعدتك اليوم؟", // الجملة التي ترغب في أن يكملها النموذج
# 		MaxTokens: 50,
# 	})
# 
# 	if err != nil {
# 		log.Fatal(err)
# 	}
# 
# 	// طباعة النتيجة
# 	fmt.Println("استجابة GPT-2: ", response.Choices[0].Text)
# }
#

!go run main.go















"""### شغال

### الخطوات لتشغيل نموذج GPT-2 محليًا باستخدام Go:
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer

# تحميل النموذج والمحول
model_name = "gpt2"
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

# توليد نص باستخدام النموذج
input_text = "مرحبًا، كيف حالك؟"
inputs = tokenizer(input_text, return_tensors="pt")
outputs = model.generate(inputs["input_ids"], max_length=100)

generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_text)

/content/go_project/gpt2_model.py


from transformers import GPT2LMHeadModel, GPT2Tokenizer

# تحميل النموذج والمحول
model_name = "gpt2"
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

# توليد نص باستخدام النموذج
input_text = "مرحبًا، كيف حالك؟"
inputs = tokenizer(input_text, return_tensors="pt")
outputs = model.generate(inputs["input_ids"], max_length=100)

generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_text)

"""
هذا الكود يقوم بتحميل نموذج GPT-2 واستخدامه لتوليد نص استنادًا إلى نص مدخل.

2. ربط Go مع Python:
بما أن Go لا يدعم مباشرة تشغيل النماذج مثل Python، يمكنك استخدام Raspberry Pi أو Docker لربط Go بـ Python عبر HTTP API أو عبر تنفيذ ملفات Python من خلال Go.

استخدام Go لتنفيذ Python: يمكنك استدعاء سكربت Python من داخل Go باستخدام مكتبة os/exec لتشغيل سكربت Python الذي يحمل نموذج GPT-2.

مثال على كيفية استخدام Go لتشغيل نموذج GPT-2 عبر Python:
إنشاء سكربت Python: احفظ السكربت السابق في ملف Python (مثل gpt2_model.py).

استخدام Go لاستدعاء سكربت Python: يمكنك تنفيذ السكربت عبر Go كالتالي:"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.go
# package main
# 
# import (
# 	"fmt"
# 	"os/exec"
# 	"log"
# )
# 
# func main() {
# 	// استدعاء سكربت Python
# 	cmd := exec.Command("python3", "gpt2_model.py")
# 	output, err := cmd.Output()
# 	if err != nil {
# 		log.Fatal(err)
# 	}
# 	// طباعة النتيجة
# 	fmt.Println(string(output))
# }
#

!go run main.go

"""شغال%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"""









"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

### شغال

### خطوات استخدام meta-llama/Llama-3.2-3B-Instruct محليًا في Python ثم من Go:
"""

/content/go_project/llama_model.py

"""gpt2_model.py"""

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "meta-llama/Llama-3.2-3B-Instruct"

# تحميل النموذج والمحزّم
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="auto")

# توليد الرد
input_text = "ارسم لي خطة دراسة لتعلم الذكاء الاصطناعي"
inputs = tokenizer(input_text, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=11)

# طباعة الرد
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""/content/go_project/llama_model.py"""

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "meta-llama/Llama-3.2-3B-Instruct"

# تحميل النموذج والمحزّم
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype="auto", device_map="auto")

# توليد الرد
input_text = "what is python?"
inputs = tokenizer(input_text, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=11)

# طباعة الرد
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

!huggingface-cli login --token XX

/content/go_project/llama_model.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main2.go
# 
# 
# package main
# 
# import (
# 	"fmt"
# 	"os/exec"
# )
# 
# func main() {
# 	cmd := exec.Command("python3", "llama_model.py")
# 	out, err := cmd.CombinedOutput()
# 	if err != nil {
# 		fmt.Println("Error:", err)
# 	}
# 	fmt.Println(string(out))
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/go_project

!go run main2.go

"""################################################ayhgشغال"""



"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"""

